sudo: required
services:
  - docker

before_install:
  - docker  build -t niranjan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run niranjan/react-test npm test -- --coverage

after_success:
  - docker build -t slniranjan/multi-client ./client
  - docker build -t slniranjan/multi-nginx ./nginx
  - docker build -t slniranjan/multi-server ./server
  - docker build -t slniranjan/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push slniranjan/multi-client
  - docker push slniranjan/multi-nginx
  - docker push slniranjan/multi-server
  - docker push slniranjan/multi-worker

# configuring deployment to AWS elasticbeanstalk
# didn't configure AWS side. just for reference here about deployment

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-13464646"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY //get from env variable in travis ci
#   secret_access_key:
#     secure: AWS_SECRET_KEY //get from env variable in travis ci




