sudo: required
services:
  - docker

before_install:
  - docker  build -t niranjan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run niranjan/react-test npm test -- --coverage

after_success:
  - docker build -t slniranjan/multi-client ./client
  - docker build -t slniranjan/multi-nginx ./nginx
  - docker build -t slniranjan/multi-server ./server
  - docker build -t slniranjan/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push slniranjan/multi-client
  - docker push slniranjan/multi-nginx
  - docker push slniranjan/multi-server
  - docker push slniranjan/multi-worker 




